### ISSUE TITLE
follow-up hack night for SF Android & iOS students after 9/26 iOS workshop - Wed Oct 14th 6-9pm

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/organizing#10]
@russbishop & [PlanGrid](http://www.plangrid.com/en/about) (__3265 17th St, Suite 404, SF__) offered to host a follow-up hack session for our past iOS students / instructors.  [The Android side of MobileBridge is planning to host a follow-up hack session 1-3 weeks after the pilot workshop.]

What local meetups (if any) host good iOS-related hack nights that we might want to partner with?

__Anyone interested in taking on organizing our first follow-up iOS hack night?__

[I can help, but can't be the lead on this one.]

**Comment by kmolo** [comment]
@russbishop how about a follow-up hack night after the next MobileBridge iOS workshop, which is 9/26 (https://github.com/mobilebridge/organizing/issues/9).  Any dates in October work for you & [PlanGrid](http://www.plangrid.com/en/about)?

**Comment by russbishop** [comment]
@kmolo Let me find out but I think we should be able to do that.

**Comment by kmolo** [comment]
Awesome!  This is pretty far in the future, so we can figure it out in September -- really anytime before the workshop.

**Comment by kmolo** [comment]
@russbishop curious if there are some October dates (post 9/26 workshop #9) when we might set up this follow-up hack session that would be work in your & PlanGrid's calendar.  If you give us some dates, then we can poll potential iOS mentors.

/cc @imju @jeffreybergier

**Comment by russbishop** [comment]
@kmolo @imju @jeffreybergier  Checking on this... sorry I dropped off the radar, it has been an extremely busy summer!

**Comment by russbishop** [comment]
@kmolo Do you know if a weekend or weekday evening is preferred?

**Comment by kmolo** [comment]
@russbishop which would work better for you & PlanGrid?

**Comment by kmolo** [comment]
A general update on our hack night efforts:

Presently SF MobileBridge is on track to have 4 iOS workshops per year, and 4 Android workshops per year, taking the summer months off.  

Ideally we're looking to have a hack night 2-3 weeks after each one.

On the Android side of MobileBridge, a small crew has taken an interest in organizing the hack nights, and focusing on getting everyone building new apps post-workshop (which is essential for them to continue on to become mobile developers).  @mdcramer and I are organizing the first Android hack night this Wed 8/26.  Looks like we're going to have a nice small working group of 7-10 people come.

On the iOS side, I'd love to a small crew who would be interested in organizing the 4 hack nights & in general encouraging our students to keep building...and, just as importantly, our volunteers to reach their own mobile goals.

**Comment by kmolo** [comment]
@russbishop when would be most convenient for you & PlanGrid to host the post-workshop hack night?

---
FYI:
At the past Android one (it was on a week night): 
- of the 25 eligible students, we had 3 RSVP that they could attend, and then only 1 could make it the night of
- of the 4 mentors that volunteered, 3 of these 4 made it the night of

For iOS, the pool of eligible students will be bigger since we'll have run 4 iOS by the time of the hack session (81 past students + however many of the 65 registered attend this one), but again, even if we invite the Android students to come & hack as well, it should be a reasonably sized group.

/cc @imju @jeffreybergier

**Comment by kmolo** [comment]
@russbishop How about a week day evening?

Here's a Doodle poll of a few weekday evenings (all Tuesdays, Wednesdays & Thursdays) 2-3 weeks after the workshop:

http://doodle.com/poll/p8ii8tygkz5makqv

...do any of these work for you and [PlanGrid](https://www.plangrid.com/en/about)?

/cc @imju @jeffreybergier @mdcramer

**Comment by mdcramer** [comment]
@kmolo I don't know iOS. Only Android and Java. Sorry.

**Comment by imju** [comment]
I will be out of town first 2 weeks of October.  November works better for
me.

**Comment by russbishop** [comment]
I think Wednesday Oct 14th works. I am confirming with our office manager. 


Also I wanted to double check what we need to provide besides the space?

**Comment by kmolo** [comment]
@russbiship if you could provide food, that would be awesome (like $100-150 worth...drinks & pizza at the last one).  But let me know if that isn't possible.

@mdcramer we'll be inviting the Android students too.  In the end, I expect we'll only get 15-20 people max.  The last one was only 4 people, so I'd say even 15 is ambitious.  Weekday evenings are hard, almost impossible for folks outside of SF to commute in for, but I think we have to be judicious of how many weekend days we ask for.  (Maybe one of our future hack sessions will be a weekend day, especially if we run it as a hackathon.)

@imju we'll have more in the future after other workshops.  Just want to keep the first post-workshop hackathon within 2-3 weeks after the workshop, so students try working on their 2nd app & then come to the workshop to get help finishing it.

Once @russbishop confirm that the 10/14 evening with the PlanGrid office manager, then we'll publicize to the wider group of teachers & TAs for this iOS workshop, to recruit who can come as mentors.

**Comment by mdcramer** [comment]
@kmolo Cool. If there's Android then I hopefully will be able to make myself available. I responded to the Doodle. For me weekday evenings work best since weekends are family time, but I certainly understand that weekday evenings are difficult for many people.

**Comment by russbishop** [comment]
@kmolo @imju @jeffreybergier @mdcramer October 14th is confirmed.

**Comment by kmolo** [comment]
yay!

**Comment by kmolo** [comment]
Here's the mentor sign-up:

http://tinyurl.com/MB-HackNight-2015-10-mentors

...students are starting to sign up & happy to say that some are students from earlier workshops who have specific apps that they're building (some really fun ones too), so looking forward to a productive hack night, helping the students figure out what Android & iOS features they need to learn about to finish their apps the way they imagine.
