### ISSUE TITLE
SF Android workshop (14-Nov-2015)

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/organizing#11]
SF MobileBridge Android is on a roll -- already starting the follow up workshop after the pilot!

A few months out:
- [x] Find a venue and sponsor for the workshop. Sponsoring the workshop costs between $400 and $900, depending on the size of the workshop. Space-wise, we usually split the students up into separate class levels, so having access to multiple workspaces would be nice (and if possible, projectors & whiteboards). Additionally, we like to offer students the option to bring their children with them (we recruit additional volunteers to help supervise so the parents can focus on coding).
  -   Dates:
      - __Teacher Training__: Sun 11/8 4-7pm
      - __InstallFest__: Fri 11/13 6-9pm
      - __Workshop__: Sat 11/14 9am - 5pm

- [ ] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)

- [ ] Select the target student population for the workshop. Our workshops reach out to a group of people that are underrepresented in the community. That might be women, people of color, non-native English speakers, LGBTQIA communities, or other marginalized groups.

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a venue, sponsors, and organizers, we can:
- [ ] Work together to set an RSVP limit that works for everyone
- [ ] Review and, if necessary, revise the computer setup instructions (newer versions, etc)
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)

One to two weeks out, we can:
- [ ] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:   
- [ ] Retro

:tulip:

**Comment by kmolo** [comment]
> https://github.com/mobilebridge/organizing/issues/7#issuecomment-115419566

@paulinar do you think uber might interested/available to host/sponsor this fall Android workshop?  (Ideally looking for a host that can provide space & cover costs.)

**Comment by kmolo** [comment]
Yay!  Thanks to @paulinar __[Uber](http://uber.com)__ is hosting!

Dates will be:
  - __Teacher Training__: Sun 11/8 4-7pm
  - __InstallFest__: Fri 11/13 6-9pm
  - __Workshop__: Sat 11/14 9am - 5pm

---

Unfortunately, those dates don't work in @ndun's schedule, so she is bumping to co-organize the Jan 2016 Android workshop, and both she & @tensory are looking for new co-organizers.  

Reply below if you want to co-organize.

**Comment by paulinar** [comment]
Hang on, I still have to get my venue request approved. :P

They're also asking for an estimate of how many people will show up -
what's our estimated headcount?



On Thu, Jul 30, 2015 at 12:58 AM, kmolo <notifications@github.com> wrote:

> Yay! Thanks to @paulinar <https://github.com/paulinar> *Uber
> <http://uber.com>* is hosting!
>
> Dates will be:
>
>    - *Teacher Training*: Sun 11/8 4-7pm
>    - *InstallFest*: Fri 11/13 6-9pm
>    - *Workshop*: Sat 11/14 9am - 5pm
>
> ------------------------------
>
> Unfortunately, those dates don't work in @ndun <https://github.com/ndun>'s
> schedule, so she is bumping to co-organize the Jan 2016 Android workshop,
> and both she & @tensory <https://github.com/tensory> are looking for new
> co-organizers.
>
> Reply below if you want to co-organize.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/organizing/issues/11#issuecomment-126215244>
> .
>



-- 
Paulina Ramos

**Comment by kmolo** [comment]
@paulinar oops, sorry.

Tonight, when Ari & I are visiting Uber for the Android curriculum session (https://github.com/mobilebridge/androidbridge/issues/1), then we can look at the space available & come up with a few possible numbers.

Thanks!

**Comment by sayor20** [comment]
Hi Guys,

My name is Sathish. I am a graduate student and CodePath Observer in the past. I am willing to volunteer if you are still looking for one. My email ID is sayor2010@gmail.com Thank you.

**Comment by kmolo** [comment]
Hi @sayor20 sorry to miss this offer on your part.  We would love to have you volunteer at the next Android workshop.

@paulinar is Uber still a possibility for the Nov dates we discussed earlier?

- Teacher Training: Sun 11/8 4-7pm
- InstallFest: Fri 11/13 6-9pm
- Workshop: Sat 11/14 9am - 5pm

Sorry, I just finished up with the last iOS workshop this past weekend, and am now looking to get this workshop back on track.

**Comment by sayor20** [comment]
@kmolo No problem. Please keep me posted. Thank you.

**Comment by kmolo** [comment]
Never confirmed organizers or venue, so closing this issue in favor of Jan/Feb 2016 Android workshop:

https://github.com/mobilebridge/organizing/issues/12

...which has 2 confirmed organizers (still looking for venue/sponsor).

**Comment by paulinar** [comment]
Hi Katherine,

My sincerest apologies for not replying, I've been out of town traveling
this past month so I'm just catching up on emails now! :( I can look into
providing a venue for Jan/Feb.

- Paulina

**Comment by kmolo** [comment]
@paulinar no worries, we didn't have the other pieces of this workshop in place, so Jan/Feb would be ideal.  Once you hear one way or the other about:

- Women of Uber possibly covering the funding of the workshop (here's a [comment discussing how much the last workshop cost](https://github.com/mobilebridge/organizing/issues/14#issuecomment-144911808))
- which Fridays, Saturdays & Sundays in Jan & Feb those rooms you showed us would be available (we need a Fri/Sat pair for the installfest & the workshop, and then an earlier Sat or Sun for the Teacher Training...the teacher training & the installfest would just need a single large space, the workshop would need all the little rooms to break out by class level)

...then comment on the new organizing issue, Issue https://github.com/mobilebridge/organizing/issues/12, to let us know.

This will be great if this works out!

/cc @ndun @wapples
