### ISSUE TITLE
SF Android workshop (23-Jan-2016)

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/organizing#12]
The SF Android workshops are on a roll!

A few months out:
- [x] Find a venue and sponsor for the workshop. Sponsoring the workshop costs between $400 and $900, depending on the size of the workshop. Space-wise, we usually split the students up into separate class levels, so having access to multiple workspaces would be nice (and if possible, projectors & whiteboards). Additionally, we like to offer students the option to bring their children with them (we recruit additional volunteers to help supervise so the parents can focus on coding).
  - __[Carbon5](http://www.carbonfive.com)__ will be hosting/sponsoring -- __woohoo!__
  - Dates:
    - __Teacher Training__: Wed 1/13 6-9pm (being held at Dev Bootcamp)
    - __InstallFest__:  Fri 1/22 6-9pm (being held at Uber)
    - __Workshop__:  Sat 1/23 9am - 5pm  (at Carbon Five)
    - __Post-Workshop Hacknight__:  Wed 2/10, 6-9pm (at Uber)

- [x] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)
  - @ndun & @wapples have volunteered to be the co-organizers!

- [x] Select the target student population for the workshop. Our workshops reach out to a group of people that are underrepresented in the community. That might be women, people of color, non-native English speakers, LGBTQIA communities, or other marginalized groups.

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [ ] Work together to set an RSVP limit that works for everyone
- [ ] Review and, if necessary, revise the computer setup instructions (newer versions, etc)
- [x] Post the workshop to [Bridge Troll](https://www.bridgetroll.org/events/236)
  - https://www.bridgetroll.org/events/236
- [ ] Post the workshop to appropriate Meetup group(s) for publicity 
  - Tip: create event on Meetup with no open RSVPs, so interested folks have to follow the link to the BridgeTroll event to register

One to two weeks out, we can:
- [x] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:   
- [ ] Retro

:tulip:

**Comment by kmolo** [comment]
@ndun has volunteered to co-organize this Android workshop & is looking for a co-organizer.

**Comment by ndun** [comment]
Confirmed workshop date - January 23rd, 2016 at Carbon 5
We are still working on the teacher training and installfest venues

**Comment by kmolo** [comment]
Definitely important that we confirm enough instructors/TAs before we post to BridgeTroll.  We will easily get students, harder is getting instructors/TAs now.

When will the teacher training be?  Last I heard we were discussing this Sat 1/9 11am - 2pm.  Is this correct/confirmed?

I know that I have to cancel some plans to make that time.  Other MobileBridge Android volunteers, what about you?  Are you available these dates?

---
I will say that Warren & Nicole worked *extremely* hard to find this sponsorship funding & hosting dates, so these dates are not easy to change.  If you can make it, please do chime in.

**Comment by Wapples** [comment]
I think the date that is most flexible right now would be the teacher training. If 1/9 proves to be too much of an issue, Dev Bootcamp was suggested as an alternative venue. I don't see a reason why we couldn't reschedule the teacher training for any day during the 11th - 15th week. 

@kmolo it would be clutch if you could help lock down a Dev Bootcamp backup space for that week.  Wednesday the 13th works for me.

**Comment by kmolo** [comment]
@wapples I'll call Dev Bootcamp about Wed 1/13.

Just on background: I'm up to my eyeballs launching a CodePath University iOS Bootcamp at City College, plus a big project kickoff at work next week.  Just saying that what I can give right now is very limited, but will do what I can (cancel my Sat plans if necessary, be at the teacher training - installfest - workshop), but I don't have the time/attention to give to this workshop the way I have been able to in the past.

**Comment by kmolo** [comment]
@nesquena @anubharadwaj @tensory @BrainScraps @kgleong @mdcramer @martasmith @nidhi1608 @sonamsharma @vibhorB @calren @k-stewart @cassiomo @AttackTheMak29 @animan1 @rtteal 

@ndun @paulinar @wapples have spent a *long* time securing space & sponsorshop for the second MobileBridge Android workshop.  

Could you be able to instruct/TA?

  - __Teacher Training__: either Sat 1/9 11am-2pm __*OR*__ Wed 1/13 6-9pm
  - __InstallFest__:  Fri 1/22 6-9pm
  - __Workshop__:  Sat 1/23 9am - 5pm

**Comment by mdcramer** [comment]
I have an appointment from 9-11am on the 23rd, but otherwise I'm available.

**Comment by kmolo** [comment]
We're getting a little crazy with the space hopping:

  - __Teacher Training__: Wed 1/13 6-9pm    --> at Dev Bootcamp
  - __InstallFest__:  Fri 1/22 6-9pm               --> at Uber
  - __Workshop__:  Sat 1/23 9am - 5pm         --> at Carbon Five

...and post-workshop hack night...TBD !!!

**Comment by kmolo** [comment]
possibility of a post-workshop hack night on Wed Feb 10th.

is that a good night for folks?

**Comment by kgleong** [comment]
@kmolo I'm available on 1/22 for the installfest

**Comment by ndun** [comment]
The event has been created on Bridgetroll. Please sign up to volunteer if you are available. Thanks!
https://www.bridgetroll.org/events/236

**Comment by kmolo** [comment]
At which Uber location is the post-workshop hack night?  1455 Market?

**Comment by kmolo** [comment]
Here's the link for mentor registration for the Wed 2/10 6-9pm post-workshop hack night:

http://goo.gl/forms/qBSJEm4CtL

**Comment by kmolo** [comment]
@Wapples @ndun @paulinar did you have the sense that anyone who attended the teacher training might be interested in organizing the next workshop?  looking for a pair of organizers.
