### ISSUE TITLE
follow-up hack night for SF Android students (26-Aug-2015)

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/organizing#13]
@mdcramer @kmolo are hosting the follow-up hack night for our past Android students:

 - WHERE: [Dev Bootcamp](http://devbootcamp.com/locations/san-francisco/) (633 Folsom St @ Hawthrone, 6th floor)
 - WHEN:  Wed, Aug 26th, 6-9pm

...attendees will be working on their next Android app.

Who's available to attend as a mentor?

/cc @animan1 @anubharadwaj @AttackTheMak29 @BrainScraps @calren @cassiomo @kgleong @martasmith  @ndun @nesquena @nidhi1608 @paulinar @rogerhu @rtteal @sonamsharma @tensory @vibhorB @wapples

**Comment by rogerhu** [comment]
Plus USB cables!
