### ISSUE TITLE
SF iOS workshop (30-Jan-2016)

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/organizing#14]
Let's get the ball rolling for our next SF iOS workshop -- here's what we need to do!

A few months out:
- [x] Find a venue and sponsor for the workshop. Sponsoring the workshop costs between $400 and $900, depending on the size of the workshop. Space-wise, we usually split the students up into separate class levels, so having access to multiple workspaces would be nice (and if possible, projectors & whiteboards). Additionally, we like to offer students the option to bring their children with them (we recruit additional volunteers to help supervise so the parents can focus on coding).
  - __[August](http://august.com/)__ is hosting us -- yay!  __[Lookback](https://lookback.io/)__ is funding the food -- double yay!.
    - __Mon Jan 25th 6-9pm - Teacher Training__
    - __Fri Jan 29th 6-7pm - InstallFest__
    - __Sat Jan 30th 9am-5pm - Workshop__

- [x] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)
  - yay! @shawnyapa, @imju, and @kmolo have volunteered to co-organize this workshop
  
- [x] Select the target student population for the workshop. Our workshops reach out to a group of people that are underrepresented in the community. That might be women, people of color, non-native English speakers, LGBTQIA communities, or other marginalized groups.

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [x] Work together to set an RSVP limit that works for everyone
- [ ] Review and, if necessary, revise the computer setup instructions (newer versions, etc)
- [x] Post the workshop to [Bridge Troll](https://www.bridgetroll.org/events/240)
  - https://www.bridgetroll.org/events/240
- [ ] Post the workshop to appropriate Meetup group(s) for publicity 
  - Tip: create event on Meetup with no open RSVPs, so interested folks have to follow the link to the BridgeTroll event to register
- [ ] If parents request childcare, recruit folks for supervised play area

One to two weeks out, we can:
- [x] Plan a teacher training
- [x] Order breakfast
- [x] Order lunch
- [x] Find a good place for the afterparty

After the workshop, we can:
- [x] Party! :tada:   
- [x] Retro
- [ ] Write a blog post

:tulip:

**Comment by kmolo** [comment]
Which Xcode do we want students to have:

https://developer.apple.com/xcode/downloads/

https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites

... also,  if students have older versions of Xcode how do they update?

**Comment by jeffreybergier** [comment]
By the time of the workshop, Xcode 7 will be out. I think it will go final on September 9th Apple event. If so we can send out a message to all students that Xcode 7 is it. It runs on OS X Yosemite and El Capitan. Then during the install feat we can make sure everyone has it. If there are still OS X Mavericks users, Xcode 6 will still work (with possible extra attention required by TA's)

**Comment by kmolo** [comment]
Sorry, I posted this to the wrong Issue.  Interested in the workshop on 9/26 - Issue #9

**Comment by yskamoona** [comment]
Dates:  

Sat Nov 7 - Teacher Training
Fri Dec 4 - Install Fest
Sat Dec 5 - Workshop

**Comment by kmolo** [comment]
Great news @yskamoona @shawnyapa!

I've invited you to the [Organizers](https://github.com/orgs/mobilebridge/teams) so you'll have [read/write access](https://help.github.com/articles/permission-levels-for-an-organization-repository/) to this issue...so you'll be able to add/remove [Labels](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/), change the Issue title, check the organizing checkboxes in the top post, etc.

Now we're focused on finding a venue, ideally one that can cover expenses (food, childcare).

**Comment by nidhi1608** [comment]
Hey @kmolo, can you please add Nick Aiwazian (@nickai) to this repo? He recently joined CodePath and will be your main contact point for everything iOS. Thanks!

**Comment by kmolo** [comment]
Thanks for making the connection @nidhi1608!  I just sent @nickai a private message within CodePath slack to arrange a time to talk & find out how best to coordinate with him.

**Comment by nidhi1608** [comment]
Thanks @kmolo!

**Comment by kmolo** [comment]
@yskamoona @shawnyapa 

---
When you log into Google Drive, you'll see a 'MobileBridge_Workshops_iOS' folder under 'Shared with me' -- Shawn, let me know if you have an alternate email you use with Google Drive.  I've created a 'iOS_2015-12' folder & pre-populated it with some of the basic working documents.

Additionally, Jeff Bergier & I will have the debriefs from the last 2 workshops up by this weekend, so you can browse thru what was said about prior workshops:

http://tinyurl.com/MB-iOS-debriefs

Yousra has a lead on a workshop location (General Assembly) and workshop funding (Expedia) -- fingers crossed as getting that secured will make smooth sailing.  By this weekend, I'll write up a more thorough accounting of costs from all the previous workshops, but roughly here's what was spent for this last one:

- Food at Teacher Training:
  - Flying Falafel - $91.92
- Food at Workshop: http://tinyurl.com/MB-iOS-2015-09-26-food
  - Noah's Bagels - $149.96
  - Safeway delivery - $137.02
  - Target (last minute cups) - $19.31
  - Palmyra lunch - $652
- Babysitting at Workshop:
  - $18/hr/babysitter -- in the future will negotiate last minute cancellation deadlines & partial payments
- 1st Drink for Volunteers after Workshop:  $75.81

We ended up buying too much lunch for last workshop as we've now slid down to the typical workshop attendance rate of 50% of registered students (despite emailing, etc) instead of the planned for 75%.  We could have only ordered 2/3rd of what we did, and would have been all set.

Palmyra was great portion size, dietary range & yummy-ness.

__Whenever you like, let's set up a time for the 3 of us to chat, so I can answer any questions you have.__

You two are *way* ahead of the game.  Keep it up, and then I really will be able to meta-organize several workshops at once (sadly I have to turn my attention back towards the next two Android workshops...we have a host & a sponsor that we've been ignoring for a whole month, so I'm going to try to resuscitate that offer).

p.s. Maybe, if Expedia is willing to cover workshop costs (approx. $1000), then we could hold the post-workshop hack night at their office, if they'd be interested.  A much smaller number of students comes to those:
- 3 of 25 Android students RSVP'ed to first hack night, in the end only 1 was able to attend (3 mentors)
- so far the RSVPs for the hack night coming up on 10/14:
  - 3 of 32 students from this latest iOS workshop
  - 2 of 102 students from prior iOS workshops (Apr-2015, Dec-2014, Sep-2014)
  - 0 of 25 students from pilot Android workshop

...BUT those that do are working on apps - which is really exciting to see!

**Comment by mdcramer** [comment]
Here's a thought for trying to boost attendance to the hack nights - Rather
than just suggest to people that they come up with projects to work on by
themselves, how about we finish up the workshops with a list of projects
that people can continue to work on at home? It could include an extension
of what's just been covered at the workshop (e.g. add a list of
functionality to the ToDo app) or any number of brand new apps for which we
could supply the initial framework or have people build from scratch. We
can then suggest that people come back to the hack nights in order to work
on or get help with these projects. I think keep people involved is
important, so perhaps this would help.

**Comment by shawnyapa** [comment]
I logged into my Google Drive at shawnyapa@gmail.com and I don't see the
'MobileBridge_Workshops_iOS'  folder. Do I need to accept an invitation or
something?

**Comment by kmolo** [comment]
@shawnyapa just shared with that email

**Comment by shawnyapa** [comment]
Yep, got it. Thanks!

**Comment by jeffreybergier** [comment]
Hey, I just watched the Rotten Tomatoes demo that Tim made for codepath. https://www.youtube.com/playlist?list=PLrT2tZ9JRrf5IZwc6TYr7vJHrsCXY9lPh

Its so quick and easy compared to ours. They use AFNetworking to set the image on the cell. Which, at the time, I thought wasn't saving very much time. But after 2 sessions of doing it manually, I think it may be worth it to revert back to that.

Also, I was thinking about how to convert this curriculum into text. While it could be done to the detail level of the current tip calculator curriculum, I was wondering why. Could we try an experiment where, in class we start and stop the videos and then type in what was typed in in the video with the class. Then at the end, the students have an exact video copy of the curriculum to step through.

What do you think?

As a fallback, we might be able to create a guide that steps through the video and explains the "Why" of some of Tim's decisions. Like why he used a ViewController instead of a TableViewController or why AutoLayout had to be turned off, etc.

**Comment by nickai** [comment]
My 2 cents...

I'm a fan of the video format. There are some things that are just so much easier to convey with video rather than text.

I haven't been to a workshop yet so I don't have a full picture on the format...but I'd be inclined to let the students watch the video and follow along with the video at their own pace while having TA's available to help troubleshoot issues or answer questions. I think this helps prevent the stronger students from getting bored while the newer students can pause and replay the video when needed.

An alternative would be to recreate the content of the video in a live setting (similar to how the CodePath classes operate). This takes more preparation on the part of the instructor, but makes the session more interactive.

**Comment by jeffreybergier** [comment]
I'm not sure i would go so far as to just let them each watch it individually. But I think if there was a "teacher" that said "OK, we're going to do this part, everyone look up here" and then played a 1 minute segment or so and then paused it. Then they could it themselves in front of the class and then everyone could go ahead and do it with the TA's.

 Then if they finished early, we might be able to say "Now do it again, individually, from the video and we'll help if you run into trouble." Or we could spend more time explaining how to make the code safer and show how you might do it "in the real world."

**Comment by timothy1ee** [comment]
For what it's worth, we've used the video format in our high school program, and it worked well. The faster students were able to move at their own pace, and the teacher was able to focus a lot of attention on the slower students.

**Comment by jeffreybergier** [comment]
Ah that is a good point. Students that move really fast often end up waiting for slower students.

**Comment by kmolo** [comment]
Hey iOS folks, we have a lead on space & funding at Expedia (yay!), and wondering if instructors/TAs would still be available for these proposed dates (especially the 11/7 Teacher Training):

- Teacher Training:  Sat Nov 7 (afternoon or early evening)
- InstallFest:  Fri Dec 4  (likely 6-7pm or 6:30-7:30pm)
- Workshop:  Sat Dec 5, 9am - 5pm
- Post-Workshop Hack Night:  some weekday evening in Jan

Not necessary that you have to be able to attend all of these, but definitely Workshop and Teacher Training (curriculum has changed since earlier teacher training).

Reply on this GitHub issues if you could be available.

Thanks!

@aparnarsjain @baw @devhut @dmtsui @dominic @dvidsilva @gwengrid @imju @Holyoke @jeffreybergier @joekim @kristen @mmesarina @mludowise @mcritz @mrh-is @nevyn @rajatb @russbishop @salilmalkan @stansey @ultrasaurus @stellasu168 @steffi06 @StephanieSzeto @timothy1ee @tjgrathwell

/cc @shawnyapa @yskamoona

**Comment by aparnarsjain** [comment]
Oh, I can’t make it to the Dec 5 workshop, I’ll be in India. :(

**Comment by mrh-is** [comment]
Looks good to me! :+1:

**Comment by dominic** [comment]
I'll be traveling Dec 5, but I'd be happy to assist beforehand if I can help out in any way.

**Comment by jeffreybergier** [comment]
I don't see anything impeding my ability to make it.

**Comment by joekim** [comment]
The dates work for me. My older brother works at Expedia.

**Comment by mludowise** [comment]
I should be available for both training and the workshop. I'll see if I can wrangle a few friends to join as well.

-Mel

Sent from my iPhone




On Wed, Oct 28, 2015 at 10:16 AM -0700, "Joseph Kim" <notifications@github.com> wrote:












The dates work for me. My older brother works at Expedia.

**Comment by imju** [comment]
Oh sorry.  I have a conflict on that day helping some activity.   :(  I owe
you coffee @yskamoona !

**Comment by mcritz** [comment]
I'm currently booked for Nov 7th. But I could potentially TA on Dec 5th

**Comment by kmolo** [comment]
UPDATE: Expedia actually isn't able to host/sponsor the event this time, but still hopes to host/sponsor an event in early 2016, so...currently we have no sponsor / host for this workshop.

The hard thing to find is the $1000 for breakfast + lunch for the workshop.  We're falling back in a two part plan: 

1) Pushing the Teacher Training back to next weekend, either Sat 11/14 or Sun 11/15, and continuing to look for sponsorship for the Dec 5th workshop date.  @yskamoona is trying to keep the existing workshop dates, so, if you know of a company (possibly your own) that would be interested in sponsoring this workshop, ask...both for the possibility of this workshop and for the possibility of future workshops.

- If you know of a company which would be interested in sponsoring, but doesn't have office space that is large enough for the workshop, this could still work -- we could hold the workshop at one of the hacker schools (Dev Bootcamp or General Assembly are happy to provide space for such learning events, but can't provide funding), and then hold the post-workshop hack night, which is a much smaller event, at the offices of sponsoring company.

2) Most likely (solely because it usually takes time go thru the process of considering & committing funding) we'll be pushing the workshop back to Feb 2016 (continuing conversations with Expedia, a new conversation with New Relic).

**Comment by stellasu168** [comment]
Hi! I can be there for the workshop but probably not on the Teacher
Training day.

On Tue, Oct 27, 2015 at 11:59 AM, kmolo <notifications@github.com> wrote:

> Hey iOS folks, we have a lead on space & funding at Expedia (yay!), and
> wondering if instructors/TAs would still be available for these proposed
> dates (especially the 11/7 Teacher Training):
>
>    - Teacher Training: Sat Nov 7 (afternoon or early evening)
>    - InstallFest: Fri Dec 4 (likely 6-7pm or 6:30-7:30pm)
>    - Workshop: Sat Dec 5, 9am - 5pm
>    - Post-Workshop Hack Night: some weekday evening in Jan
>
> Not necessary that you have to be able to attend all of these, but
> definitely Workshop and Teacher Training (curriculum has changed since
> earlier teacher training).
>
> Reply on this GitHub issues if you could be available.
>
> Thanks!
>
> @aparnarsjain <https://github.com/aparnarsjain> @baw
> <https://github.com/baw> @devhut <https://github.com/devhut> @dmtsui
> <https://github.com/dmtsui> @dominic <https://github.com/dominic>
> @dvidsilva <https://github.com/dvidsilva> @gwengrid
> <https://github.com/gwengrid> @imju <https://github.com/imju> @Holyoke
> <https://github.com/Holyoke> @jeffreybergier
> <https://github.com/jeffreybergier> @joekim <https://github.com/joekim>
> @kristen <https://github.com/kristen> @mmesarina
> <https://github.com/mmesarina> @mludowise <https://github.com/mludowise>
> @mcritz <https://github.com/mcritz> @mrh-is <https://github.com/mrh-is>
> @nevyn <https://github.com/nevyn> @rajatb <https://github.com/rajatb>
> @russbishop <https://github.com/russbishop> @salilmalkan
> <https://github.com/salilmalkan> @stansey <https://github.com/stansey>
> @ultrasaurus <https://github.com/ultrasaurus> @stellasu168
> <https://github.com/stellasu168> @steffi06 <https://github.com/steffi06>
> @StephanieSzeto <https://github.com/StephanieSzeto> @timothy1ee
> <https://github.com/timothy1ee> @tjgrathwell
> <https://github.com/tjgrathwell>
>
> /cc @shawnyapa <https://github.com/shawnyapa> @yskamoona
> <https://github.com/yskamoona>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/organizing/issues/14#issuecomment-151610429>
> .
>



-- 
Stella Su

**Comment by kmolo** [comment]
Hi everyone, still looking for sponsorship for this workshop -- lots of good leads, but no final 'yes' yet, so keep asking -- so we're bumping it back to February after the holidays.

**Comment by kmolo** [comment]
The next Mobilebridge iOS workshop is a go -- thanks to @shawnyapa and his company [August](http://august.com/):

https://www.bridgetroll.org/events/240

...here are the confirmed dates:

    - __Mon Jan 25th 6-9pm- Teacher Training__
    - __Fri Jan 29th 6-7pm - InstallFest__
    - __Sat Jan 30th 9am - 5pm - Workshop__

...now we're in the full court press to recruit instructors/TAs -- once we recruit enough volunteers can increase the number of spaces for students.

**Comment by kmolo** [comment]
Additionally, there'll be a hack night at Uber on Wed Feb 10th.

**Comment by mcritz** [comment]
I would love to attend, perhaps as a T.A.

**Comment by nevyn** [comment]
Me too!

**Comment by jeffreybergier** [comment]
@nevyn @mcritz make sure to register as a volunteer at this link: https://www.bridgetroll.org/events/240

**Comment by stellasu168** [comment]
I can make it on hack night. How do I sign up? Thanks!

On Mon, Jan 11, 2016 at 4:07 AM, kmolo <notifications@github.com> wrote:

> Additionally, there'll be a hack night at Uber on Wed Feb 10th.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/organizing/issues/14#issuecomment-170521573>
> .
>



-- 
Stella Su

**Comment by cbowns** [comment]
I'd love to see https://www.bridgetroll.org/events/240 announced on the https://twitter.com/mobilebridgesf account.

**Comment by shawnyapa** [comment]
Hey Christopher,

Good point!

This is the first event I've been involved with actually organizing and I'm
guessing there are a bunch of these things that I'm missing besides Twitter.

Are there other places this should be posted?
And does Katherine own the twitter account/

-shawn

On Mon, Jan 18, 2016 at 9:28 AM, Christopher Bowns <notifications@github.com

**Comment by nevyn** [comment]
Does this event still need funds? I could look into Lookback sponsoring it.

**Comment by imju** [comment]
We just managed to fund it.  The event is good to go.  Hey, you can sponsor
some of the upcoming ones.  I think we got the next sorted.  Probably after
that.

**Comment by kmolo** [comment]
@imju, we have not funded this workshop -- @shawnyapa & I are paying for it out of pocket.
@nevyn, if Lookback can contribute that would be awesome.  Here are details of what we paid last time:
https://github.com/mobilebridge/organizing/issues/14#issuecomment-144911808

...right now @shawnyapa is paying for the workshop lunch, so that might be the best thing to contribute towards; I'm covering food at teacher training, and @shawnyapa is also covering first drink for volunteers at after-party (which has only run like $60 tip included at past events).  No childcare offered this time.

**Comment by kmolo** [comment]
@cbowns @shawnyapa my bad, I do have the Twitter account, but hadn't created the tweet earlier -- here it is:

https://twitter.com/mobilebridgesf/status/689278446942355456

...we already have a waitlist of 59 students, so didn't create a similar Tweet directed at students.

**Comment by imju** [comment]
Ok. Do we need physical meeting for teacher training?  Can we use hangout? If funding is tighter.

Thanks,
Imju

<div>-------- Original message --------</div><div>From: kmolo <notifications@github.com> </div><div>Date:01/18/2016  6:43 PM  (GMT-08:00) </div><div>To: mobilebridge/organizing <organizing@noreply.github.com> </div><div>Cc: imju <imjubyon@gmail.com> </div><div>Subject: Re: [organizing] SF iOS workshop (30-Jan-2016) (#14) </div><div>
</div>@imju, we have not funded this workshop -- @shawnyapa & I are paying for it out of pocket.
@nevyn, if Lookback can contribute that would be awesome. Here are details of what we paid last time:
#14 (comment)

...right now @shawnyapa is paying for the workshop lunch, so that might be the best thing to contribute towards; I'm covering food at teacher training, and @shawnyapa is also covering first drink for volunteers at after-party (which has only run like $60 tip included at past events). No childcare offered this time.

**Comment by kmolo** [comment]
I think it's valuable to be in-person for the teacher training.  Plus technical challenges of so many people.

The big expense is feeding folks the day of the workshop.  

Had a long conversation with @ultrasaurus about the to-provide-food-or-not-to-provide-food question (for an earlier workshop), and I agree with her that food is important for a number of reasons (maintaining mental alertness over long day, creating the space during lunch for the community to form, removing economic distinctions, having people return for the after-lunch period).

**Comment by dvidsilva** [comment]
sorry late to the party, I see there are a lot of teachers and TA so I didn't sign up, but I'm free that day if there's need for more.

**Comment by kmolo** [comment]
@stellasu168 and others:  
here's the link for the mentor registration for the Wed 2/10 6-9pm post-workshop hack night

http://goo.gl/forms/qBSJEm4CtL

...Uber is hosting + providing dinner (they're one of the hosts/sponsors of the Android workshop on 1/23).

It'll be both students from the Android workshops + the iOS workshops, recruiting mentors for both technologies.  But won't be sharing the student sign-up link until the day of the workshop, in order to give the students at that workshop time to sign up.

So far these have been pretty small affairs (12 including mentors at the last one), but probably will grow, especially now that we have more post-workshop projects to offer students courtesy of CodePath University:

https://github.com/mobilebridge/iosbridge/issues/12

**Comment by nevyn** [comment]
@kmolo That links sounds like roughly $1000? Lookback would love to sponsor that. We've never donated before so don't know exactly how that works. We'd of course love to have logo featured, and do we get a small intro to talk about our company during the event?

**Comment by kmolo** [comment]
@nevyn that would awesome!  

Generally, companies will either pay directly for the food, or reimburse MobileBridge volunteers when provided receipts.  The first is easier for us, but sometimes companies can't do that.

Let us know which Lookback could do.

And which logo you'd like to use -- https://lookback.io/press -- I'm thinking this one:
https://d183seq046c5ro.cloudfront.net/images/logos/lookback/logo-black.png

...will be in good contrast with August's:
https://www.bridgetroll.org/events/240

You definitely get to have 5-minutes to tell everyone what Lookback does as we thank you + August for sponsoring + hosting.  Plus we'll be tweeting thank yous.

**Comment by imju** [comment]
Teacher training agenda
https://docs.google.com/document/d/1fGruC09Xc_nZWlZ4nWbHJWLJDRD6FY_3Sd7CzMCOCyg/edit?usp=sharing

**Comment by nevyn** [comment]
@kmolo OK! Could we discuss it during the teacher training? Haven't done stuff like this before.

**Comment by nevyn** [comment]
Worked it out with my accountant! I can pay for the food with my company card, and for the things you've already paid for, you can file an expense report and we'll pay it back.

**Comment by imju** [comment]
Welcome @originaldon @cbowns @sjwn @grossmae

**Comment by imju** [comment]
Should we increase attendance limit to 50 from 30?  It will still be around 25 actual attendance in my guess.

**Comment by nevyn** [comment]
I think so! If the venue can take it.

**Comment by imju** [comment]
OK.  I moved up the number to 50.  I project it will be around 30 in actual
that matches to original cap.
@nevyn  I included Lookback info.  https://www.bridgetroll.org/events/240
Thanks for stepping up.

**Comment by jeffreybergier** [comment]
Hey everyone, I wanted to give a shout out to @krotondo who just registered to volunteer for the workshop on Saturday. Kathryn is an amazing iOS developer and has been teaching the iOS Development class at General Assembly. She is going to make a great addition to the MobileBridge/BridgeTroll group! :+1: :100:

**Comment by cbowns** [comment]
@imju @kmolo I got a chance to look over my notes from last night's training: I think I need to notch my participation back from "teacher for the course" to a co-teaching position for my track. I've set aside some time between now and Saturday to review the material, but since this is my first MobileBridge, I think I want to share teaching time with someone with more experience. Drop me an email if y'all want to chat about this more!

**Comment by imju** [comment]
@krotondo Welcome!

@cbowns We will look around to find someone to pair up to divide the course
with you.  But even as alone, with help from TA, you should be awesome.

**Comment by mludowise** [comment]
@the8bitdeity Adding Rob who will also be TAing Saturday.

**Comment by kmolo** [comment]
Here's the teaching plan so far:

http://i.imgur.com/SRXCeEr.jpg

blue = beginners (no coding experience) 
- teaching split up among @dominic @grossmae @mludowise @sjwn

green = adv beginners
- @jeffreybergier teaching his new RottenTomatoes curriculum:
https://github.com/mobilebridge/iosbridge/issues/13
- other parts of teaching can be split up with @the8bitdeity @shawnyapa @krotondo @danthaman44 (Tim Garcia):
--> intro to anatomy of iOS apps, using either apps on your iPhone displayed via Quicktime or
http://www.mobile-patterns.com/
http://www.pttrns.com/
--> creating a new project + then tour of Xcode IDE
--> RT ( @jeffreybergier )

gold = some prior iOS experience (usually attending our workshop before)
-- teaching the original Rotten Tomatoes curriculum (all from scratch, no starter project):
https://github.com/mobilebridge/iosbridge-rottentomatoes
-- both @mcritz + @imju have taught this before, @cbowns + @originaldon also in this section
-- the 4 of you can decide who should teach which section

orange = experienced programmer, new to iOS (also 1 student with prior iOS experience)
-- @mrh-is @nevyn @kristen have taught this before, also @akanshmurthy + @holyoke here
-- teaching the original Rotten Tomatoes curriculum (all from scratch, no starter project):
https://github.com/mobilebridge/iosbridge-rottentomatoes

---
After the workshop, we're inviting the students from this workshop + all prior MobileBridge workshops to a hack night -- Wed Feb 10th 6-9pm at Uber (1455 Market St, SF).

Luckily, because of the @codepath University bootcamp being piloted right now, we have lots of additional curriculum to give students to work on post-workshop:

https://github.com/mobilebridge/iosbridge/issues/12

...some is usable as-is, some we need to build out.

**Comment by kmolo** [comment]
RSVP for mentors for Wed Feb 10th 6-9pm hack night at Uber:

http://tinyurl.com/MB-hack-night-mentors-20160210

**Comment by kmolo** [comment]
Finally, just wanted to point out the organizing issue for the next iOS workshop:

https://github.com/mobilebridge/organizing/issues/17

... @mrh-is is looking of a co-organizer + a merry band of instructors/TAs + a hosting/sponsoring company/companies.  

Chime in on that issue if you can help on any of these fronts!

**Comment by kmolo** [comment]
Install question: 
- student has OS X 10.11 El Capitan, but Xcode 7.0.1

...should they upgrade their Xcode, or is 7.0.1 fine?

**Comment by kmolo** [comment]
Install question:
- student has OS X 10.11 El Capitan, but Xcode 7.0.1

...should they upgrade their Xcode, or is 7.0.1 fine?

**Comment by nevyn** [comment]
I think 7.0.1 should be fine; no major changes to Swift that I can think of

**Comment by kmolo** [comment]
Thanks @nevyn!

**Comment by nevyn** [comment]
Ooh, problem is if they run 9.2.1 on their phone, they might need 7.2. Couldn't verify that that was the problem, but seems likely.

**Comment by nevyn** [comment]
This is what the student downloads: https://github.com/jeffreybergier/ga-sf-ios4-top-movies/tree/tableview-starter-project

**Comment by stellasu168** [comment]
Hi, I am unable to make it to hack night tonight. I just started my new job
this week so things are kind of crazy. I'd love to join next time.
hopefully soon!!

On Tue, Jan 19, 2016 at 4:23 AM, kmolo <notifications@github.com> wrote:

> @stellasu168 <https://github.com/stellasu168> and others:
>
> here's the link for the mentor registration for the Wed 2/10 6-9pm
> post-workshop hack night
>
> http://goo.gl/forms/qBSJEm4CtL
>
> ...Uber is hosting + providing dinner (they're one of the hosts/sponsors
> of the Android workshop on 1/23).
>
> It'll be both students from the Android workshops + the iOS workshops,
> recruiting mentors for both technologies. But won't be sharing the student
> sign-up link until the day of the workshop, in order to give the students
> at that workshop time to sign up.
>
> So far these have been pretty small affairs (12 including mentors at the
> last one), but probably will grow, especially now that we have more
> post-workshop projects to offer students courtesy of CodePath University:
>
> mobilebridge/iosbridge#12
> <https://github.com/mobilebridge/iosbridge/issues/12>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/organizing/issues/14#issuecomment-172835936>
> .
>



-- 
Stella Su

**Comment by nevyn** [comment]
So the workshop is today? The web site says Jan 30: https://www.bridgetroll.org/events/240

**Comment by sjwn** [comment]
Hi Nevyn,

Imju wrote this in her last email that was sent to all the students too --
see you there, maybe :)

Sam



--



Would you like to get some help from experienced developers and finish up
project? FollowUp HackNight at Uber - Students and Mentors, Please signup!
Wed. Feb. 10 6-9pm
@Uber (1455 Market St, SF)
Student sign-up: http://tinyurl.com/MB-HackNight-2016-02
Mentor sign-up: http://tinyurl.com/MB-HackNight-2016-02-Mentor

On 10 February 2016 at 16:50, Nevyn Bengtsson <notifications@github.com>
wrote:

> So the workshop is today? The web site says Jan 30:
> https://www.bridgetroll.org/events/240
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/organizing/issues/14#issuecomment-182660440>
> .
>



-- 
*Samantha Wong*
415.881.0807

**Comment by nevyn** [comment]
My bad! I mixed up workshop and hack night, sorry :) I'm not feeling too good but I'll swing by if I can after work.

**Comment by nevyn** [comment]
Gah, I forgot to fill in the registration so they're not letting me in, and I don't have Imju's number :(

**Comment by nevyn** [comment]
@imju We are missing the iOS students from the security guest list. Could you share the results sheet from the form at https://docs.google.com/forms/d/1STUDoqBRrpt8dyI_ueCLLIaMJmY3VB1DJq5-8d-rV_s/viewform?fbzx=-8565626644499262499 ? 

Thanks!

@ndun needs it :)

**Comment by imju** [comment]
Oh, I missed this email. Sorry. @nevyn   My gmail was unreachable last
night on my phone because of some mistake that I made on the security
setting.  I wasn't aware of handing out list to Uber before either.

https://docs.google.com/spreadsheets/d/1b3XArC5YhxN0RRM2ZsMHjP0WDC_JPZJVC_XRiOwCWlw/

How did it go?!

**Comment by imju** [comment]
Sorry for the mishap, last night.  We will do a better job next time.  I am closing this issue as we are done with the hacknight.  
I think we really need to revisit the group assignment in the mobile bridge.  I will open a new issue with that.  But closing this one.  Thanks again to all!
