### ISSUE TITLE
Issue for Jeff and Imju to Organize event 182

### ISSUE THREAD

**Issue by jeffreybergier** [mobilebridge/organizing#15]
To Do’s from Skype Call:

- [x] Jeff - Email Half of the Volunteers (Listed below)
- [x]  Jeff - Provide sample email
- [x] Jeff - Find Katherine’s Teacher Training Google Doc
- [x] Imju - Email Other half of Volunteers
- [x] Imju - Email Pivotal guy to see how we can get it (Jeff can get a key from him tomorrow at his office if needed)

[Jeff will email:]
sandi ma
Michael Critz
Michael Helmbrecht
Russ Bishop
Yousra Kamoona

[Sample Email]
Hi [Michael],

Thanks so much for volunteering with Mobile Bridge for the Beginning iOS Development workshop on Friday and Saturday September 25 and 26. https://www.bridgetroll.org/events/182.

Imju and I are organizing this event and we wanted to make sure that you were still able to make it to the Pivotal Labs offices on Saturday 9/26. Saturday is the most important day. It would also be great to have your help on Friday evening for the install fest.

We also realized we made a boo-boo by scheduling the teacher training when the BART is closed. Let us know if you can make it or not. If not, we will try to arrange a second (possibly virtual) teach training.

Lastly, we are a little understaffed for volunteers for this workshop. It would be a huge favor to us and our students if you could each tell 2 or 3 Cocoa friends about the workshop and ask them to volunteer. Tell them not to worry if they can’t do the teacher training (since its so soon), Imju and I will make sure are up-to-date on the teacher training. We really just need some more people with Xcode experience in the rooms.

Thanks again for volunteering. Please reply to this email and let us know:
1) Whether you can make it on Saturday and/or Friday
2) If the Sunday teacher training if possible
3) How many friends you asked to volunteer (so we can praise/shame you :p)

-Jeff and Imju
949 287 1699
jeffburg@jeffburg.com
https://www.bridgetroll.org/events/182

**Comment by jeffreybergier** [comment]
sandi ma
Michael Critz
Michael Helmbrecht
Russ Bishop
Yousra Kamoona 

are all emailed. No responses yet.

**Comment by jeffreybergier** [comment]
Here is the document that we can use as a template for the teacher training schedule https://docs.google.com/document/d/15UY9pYuCCPqc3eMl3x19OkmhyGawgcYzGHxUl0gwoos/edit?pli=1

**Comment by imju** [comment]
Emails sent to Pivotal team and my part of Volunteers. No response yet.

**Comment by kmolo** [comment]
@imju @jeffreybergier one thing that worked really well at the teacher training for the Android was leaving time at the end of the workshop for the instructors & TAs to plan who would teach each section, particularly helping the TAs have a little section to teach.

**Comment by jeffreybergier** [comment]
@kmolo @imju I got the key for pivotal. 

So far I have 3 responses. 1 can make it on Sunday. All can make it for the actual workshop. 

Waiting for responses from 2 volunteers.

**Comment by kmolo** [comment]
@jeffreybergier for those can't make it, please have them update their RSVPs on Bridgetroll, so that they uncheck the Teacher Training session.

We don't want people to become accustomed to their Bridgetroll RSVPs not being the definitive source of their status.

**Comment by jeffreybergier** [comment]
@kmolo @imju here is the chat thing I was talking about that makes it super easy to share links in classrooms. https://tlk.io/

**Comment by kmolo** [comment]
@jeffreybergier @imju can we close this issue & pull any additional discussion into the main organizing issue #9?

**Comment by jeffreybergier** [comment]
Sure
