### ISSUE TITLE
meta-organizing MobileBridge

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/organizing#5]
Who wants to work on building a sustainable MobileBridge community?

**Comment by xenadu** [comment]
I don't know how much I can help but I'm certainly willing to pitch in

**Comment by kmolo** [comment]
[Summary of prior conversations]

Presently MobileBridge has 2 curricula, [iosbridge](https://github.com/mobilebridge/iosbridge) & [androidbridge](https://github.com/mobilebridge/androidbridge).  We started with the iOS workshops -- 3 so far (2 in SF, 1 in Hawaii) and [1 upcoming in SF](https://github.com/mobilebridge/organizing/issues/4) -- and then plan for the pilot Android workshop to be later this year.

Our idea was to rough out the curriculum materials, and then widely publicize.  Based on the [debrief feedback we have so far](https://github.com/mobilebridge/organizing/issues/4#issuecomment-74412712), we hope to have the  flow of a 1-app workshop after this upcoming SF workshop, but maybe not all the supporting reference materials. /cc @jeffreybergier 

After that, we had talked about growing the MobilebridgeSF community:
* hosting a Fall 2015 iOS workshop at a larger venue (like a Carbon Five or Pivotal), and 
* organizing a big teacher/TA/volunteer training & encouraging all past workshop participants to join

To support this jump, we had talked about trying out a [similar organizational structure to the one that RailsbridgeSF just adopted](https://www.bridgetroll.org/events/123):
* an Organizer Manager who finds & supports organizers
* a Venue Manager who finds & supports hosts/sponsors
* a Chapter Lead who supports the Organizer Manager & the Venue Manager

Once a potential workshop has organizers & hosts, these folks handle all the arrangements for the individual events.

At some point in the future, as the MobileBridge community grows, there probably will be more (curriculum developers, outreach folks, etc):

http://railsbridge.org/about/team
http://docs.railsbridge.org/docs/
https://groups.google.com/forum/#!forum/railsbridge-workshops
https://groups.google.com/forum/#!forum/learning-android-development-organizers
https://groups.google.com/forum/#!forum/learning-ios-development-organizers

...but the overarching keystone is to build a great community.

[There are discussions on the Railsbridge Google Group & in BridgeTroll feature requests, which describe the problem of having too many volunteers show up to workshops.  It would be amazing for MobileBridge to have to deal with this *problem* some day.]

**Comment by jeffreybergier** [comment]
Hey, I don't want to hijack the thread too much. But I wanted to get everyone's opinion. There was a lot of feedback from the last session that the tip calculator app didn't leave enough time for the rotten tomatoes app. I definitely agree with this feedback, but I also felt like the tip calculator app is the key to understanding how the XIB/Storyboard is connected to the code. So I was thinking of solutions to this and I was going to start a new curriculum guide for instructors that had the following basic sections.

- Section 1) Understanding Interaction Paradigms on iOS
     - Emphasis that this whirlwind 6 hour session of iOS will NOT teach all of iOS. 
     - Also emphasize that a lot of the code and syntax we are just going to ignore and go with the flow. Previous feedback showed the Objective C overview was not that useful. Either the experience level of the students is such that it goes right over their heads or they already fundamentally understand the concepts and the syntax is just syntax and is not a big deal.
     - This section is off the computer. The instructor will whiteboard and show the students the basic interaction paradigms in iOS.
     - The 4 fundamental ones are probably UIViewController, UINavigationController, UITabBarController and UITableView / Controller.
- Section 2) Fundamentals of Connecting XIB/Storyboard to Code
     - In this section, the instructor will walk the students through building a UIViewController that has a button and a text field and a label. 
     - Clicking the button will take the text from the textfield and put it into the label.
     - I think this will teach the IBAction / IBOutlet / Communication paradigm taught by the tip calculator but be much faster
- Section 3) Build the UI for the Rotten Tomatoes App
     - This is where the instructor will walk the students through the concept of "Prototype" cells
     - Connect a single UILabel in the cell to a UITableViewCell subclass
     - Then changing the label in the tableViewCellForRowAtIndexPath
     - Lastly, preparing the labels and images needed for the rotten tomatoes app
- Section 4) Download the Rotten Tomatoes JSON and Parse it and Connect it to the TableView
    - Use NSURLSession to download the rotten tomatoes JSON file
    - Parse it with NSJSONSerialization (see the dictionary in the debugger)
    - Learn how to take this array and put it into tableViewCellForRowAtIndexPath to populate the TableView
    - If we make it this far, show how to download the images with NSURLSession for the cells (this is tricky because of the way iOS recycles cells).

**Comment by kmolo** [comment]
@jeffreybergier you could take your previous post & open a new issue in the [mobilebridge/iosbridge](https://github.com/mobilebridge/iosbridge) repo, similar to this one from Nov 2014:

https://github.com/mobilebridge/iosbridge/issues/3

...that way the discussion can expand in its own issue & stay in the history of the [iosbridge](https://github.com/mobilebridge/iosbridge) repo.

**Comment by jeffreybergier** [comment]
@kmolo Great idea. Link to new issue is here if anyone wants to comment. https://github.com/mobilebridge/iosbridge/issues/5

**Comment by jeffreybergier** [comment]
@kmolo whoops. Wrong button.

**Comment by kmolo** [comment]
@jeffreybergier I do that all the time. :bowtie:

**Comment by mfjenn** [comment]
Wow. I am so happy to see the enthusiasm has grown for mobile bridge since the first time Nathan, Tim & I sat down to talk about doing mobile workshops! 

I hope to see some workshops happen here in the Twin Cities, where I am now. 

I don’t mean to throw a curveball into things, but I want to let you know that Bridge Foundry, the parent organization of all the “Bridges” is here to support you. 

Here is some documentation <https://atrium.schoolfactory.org/bridgefoundry/node/108426> about how we can facilitate and support fundraising efforts — from invoicing larger donors who wish to make a tax-deductible donation, to simply creating a customized Paypal donation button to place on your website so people who love what you are doing can drop a few dollars in your bucket when they visit. :) 

Links to all the information is at the left of that page. 

If you think your organization would like to use the support we offer, it would be great if someone could step up as a Financial liaison who can review the balance spreadsheet quarterly for accuracy and maybe answer questions occasionally. 

Let me know if you have any questions. 

Go MobileBridge! 

Mary F. Jenn
Operations Manager
Bridge Foundry
maryfjenn@gmail.com <mailto:maryfjenn@gmail.com>
tel: 415.290.0587

www.maryfjenn.com <http://www.maryfjenn.com/>
www.bridgefoundry.org <http://www.bridgefoundry.org/>
skype: mfjenn
twitter: maryfjenn
Github <http://github.com/mfjenn>
LinkedIn <http://www.linkedin.com/pub/mary-jenn/4/aa2/8aa>

**Comment by kmolo** [comment]
thanks @mfjenn, that's something we'll definitely consider in the future (just get MobileBridge and mostly MobileBridgeSF launched).

**Comment by kmolo** [comment]
Also thought I'd point out the latest *Bridge -- [ngBridge](https://github.com/ng-bridge/organizing) (AngularJS).

They were [inspired by MobileBridge](https://twitter.com/bjbrennan75/status/574988473968427010) and forked our organizing repo to start their own, and are [now planning 3 workshops in SF, Utah, and the Baltimore/DC area](https://github.com/ng-bridge/organizing/issues).

**Comment by mfjenn** [comment]
Thanks! I know Judys been in touch w Sarah so she may already know. I'll check in with Sarah to see if they talked about it at all. 

Please excuse my brevity. Sent from my iPhone

**Comment by kmolo** [comment]
Another area to work on:
- Need to provide clear next steps for students to continue working on apps after the workshop.
- Also how can students stay in touch & support each other?

Related to these, a number of students have asked for access to materials before the workshop, so they could explore & prepare to get more out of the workshop.

**Comment by jeffreybergier** [comment]
@kmolo I intent to add a section on basics of app design and interface paradigms. I should probably also find ways to add "next" steps at the end of the curriculum.

As far as students contacting each other and their instructors, perhaps we could create a wiki page on github for each classroom? Students can add contact info or app ideas or anything they feel comfortable with? Not sure... just an idea.

**Comment by ultrasaurus** [comment]
There's talk about setting up Discourse forum for Bridge Foundry where students could ask follow-up questions.  We do need at least one volunteer moderator for each technology... anyone want to help kick that off for iOS?

**Comment by jeffreybergier** [comment]
Hey everyone,

I finished most of the curriculum I was planning to go over tomorrow. I could certainly use a fresh set of eyes on this. If anyone has time, could you read over it and make sure the guide makes sense, teaches the right things and has enough detail? Also, I'm a bit worried about the tone. Does it sound instructional without being condescending?

https://github.com/jeffreybergier/RottenTomatoesGuide/wiki

Thanks!
-Jeff

**Comment by ultrasaurus** [comment]
@jeffreybergier I'll give it a whirl since my eyes are starting to glaze over with my third TipCalculator...

I've written up an alternate TipCalculator that uses Swift and steps that are a little easier (based on what @timothy1ee taught in the first workshop).  It's not quite done, but I need a break from it -- this is designed as teacher notes.  I would love additional tips of what you would mention if you were teaching:  https://github.com/ultrasaurus/swift-tipster  -- I think there are spots where I should intentionally create errors and tell people what to look for.

**Comment by ultrasaurus** [comment]
Can we move https://github.com/jeffreybergier/RottenTomatoesGuide/wiki/Class-Introductions to a general place?  I'd like to combine Tim's "Spanish reading glasses" with @jeffreybergier's "Beer Glasses"  -- the general intro stuff is applicable for all levels.

@jeffreybergier would you be willing to factor out your intro and combine with the info here:  https://github.com/mobilebridge/iosbridge/wiki/iOS-1-day-Weekend-Workshop ?  (there should be a page with schedule -- which has good structured breaks, that doesn't reference a specific curriculum)

**Comment by ultrasaurus** [comment]
@jeffreybergier I think we need to assume that at least one group will be experienced programmers who are just new to iOS.  Let's not assume that something is confusing...

"The Cell recycling is another concept that is really hard to understand, and for now, its best to not mention it or mention it will be explained later." 

I haven't done this in iOS, but I'll bet it is really similar to things I've done before in C++ and JavaScript.  Can you phrase this in terms of a conceptual question that would suss that out?  I still think it is a good idea not dive into detail about this yet, but let's not treat experienced coders as if they have never run into this idea, just in case they have.  

Side note:  I worry sometimes that *Bridge workshops can alienate experienced developers in an attempt to be welcoming to novices.  It's a delicate balance, but when we get it right, the experienced people in the room get an amazing learning experience AND serve as mentors and role models to the novices (in that we are all always learning new stuff in this industry).

Sorry -- need to step aways for a half hour or so.  Next I'll go through the whole thing and save feedback for the end.  

Thank you!

**Comment by jeffreybergier** [comment]
@ultrasaurus great input. I definitely agree. I adjusted the language in this case to encourage the Instructor to gauge the knowledge level of the class and get as deep as they like. I probably need to do the same in other parts of the curriculum. Also, this is a shortcoming of mine since the only development environment I know is iOS. There is definitely room for more experienced volunteers to add bullet points like "If you're familiar with X, then this topic is like Y in X language.

I'll bring this up at teacher training tomorrow.

**Comment by jeffreybergier** [comment]
@ultrasaurus you mentioned the beer goggles / glasses. I actually meant to use Tim's "spanish reading glasses" and just mis-remembered it :p

And yes. I think the general information on running the class should be in a generic place. Maybe we can figure out a good way to do that before next saturday.

**Comment by Zaipee** [comment]
https://github.com/mobilebridge/organizing/issues/16

**Comment by Zaipee** [comment]
kmolo opened this issue over 3 years ago

**Comment by Zaipee** [comment]
https://github.com/mobilebridge/organizing/issues/16

**Comment by Zaipee** [comment]
#5
