### ISSUE TITLE
Request for proposals to DroidCon Berlin

### ISSUE THREAD

**Issue by rachelmyers** [mobilebridge/organizing#6]
Feel free to close this if this is the wrong way to get this in front of people. :grimacing: 

A note came into hello@railsbridge.org from the diversity advisor of [DroidCon Berlin](http://droidcon.de/), asking for any [talk proposals](http://droidcon.de/call-papers) that people have been thinking of giving! And if it's easy for anyone, I think they're also hosting a [meetup](https://www.facebook.com/events/1560272974213859/)??

If anyone has questions, I can forward the email.

:hibiscus:

**Comment by nesquena** [comment]
I think this is great, if you forward the email, I am happy to pass this along to other alumni that might be interested in speaking there. I have a few engineers in mind that helped us form and run some of our android workshops who might be interested in submitting.

**Comment by rachelmyers** [comment]
@nesquena Awesome! Done!
