### ISSUE TITLE
SF MobileBridge Pilot Android Workshop (8-Aug-2015)

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/organizing#7]
Let's get the ball rolling for our pilot SF MobileBridge Android workshop!

A few months out:
- [x] Find a venue and sponsor for the workshop.The workshop will consist of 3 separate parts -- a teacher training, an installfest (typically the Friday night before the workshop), and the Saturday workshop itself.  Space-wise, we usually split the students up into separate class levels, so having access to multiple workspaces would be nice (and if possible, projectors & whiteboards).  Additionally, we like to offer students the option to bring their children with them (we recruit additional volunteers to help supervise so the parents can focus on coding).
  - Hearsay Social is able to host, but cannot cover the food:
      - __Teacher Training:  Sat, Aug 1st, 2-5pm__
      - __InstallFest:  Fri, Aug 7th, 6-9pm__
      - __Workshop:  Sat, Aug 8th, 9am - 5pm__

- [x] Find additional sponsorship for the workshop
  - Sponsoring the workshop costs between $400 and $900, depending on the size of the workshop. 

- [x] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)
  - yay! @BrainScraps and @nidhi1608 have volunteered to co-organize this workshop

- [x] Select the target student population for the workshop. Our workshops reach out to a group of people that are underrepresented in the community. That might be women, people of color, non-native English speakers, LGBTQIA communities, or other marginalized groups.

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a venue, sponsors, and organizers, we can:
- [x] Work together to set an RSVP limit that works for everyone
- [ ] Review and, if necessary, revise the computer setup instructions (newer versions, etc)
- [x] Post the workshop to [Bridge Troll](https://www.bridgetroll.org/events/177)

https://www.bridgetroll.org/events/177

One to two weeks out, we can:
- [x] Plan a teacher training
- [x] Order breakfast
- [x] Order lunch
- [x] Find a good place for the afterparty

After the workshop, we can:
- [x] Party! :tada:   
- [x] Retro

:tulip:

**Comment by kmolo** [comment]
Who's interested in being involved in the pilot SF MobileBridge Android workshop?

**Comment by tensory** [comment]
Hi, kmolo! I'm interested! Really happy to see you are getting this started.

**Comment by jeffreybergier** [comment]
I normally help with the iOS MobileBridge. I don't know anything about android... but I'd be super interested in being a student.

**Comment by nesquena** [comment]
I tweeted about this from my personal and codepath accounts and also posted this to our alumni group that goes out to hundreds of our iOS and Android alumni. Hoping to bring in more support to make this event happen. Thanks @kmolo for leading the charge with this, going to be exciting to have the first Android event!

**Comment by tensory** [comment]
What can I do to help?

**Comment by vibhorB** [comment]
@kmolo I would be happy to help with teaching and prep for class

**Comment by kmolo** [comment]
First, we're looking for 2+ folks to step up to organize the pilot Android workshop. They'll have \*lots* of help from me, @nesquena and many others.

Next, we're looking for a venue/sponsor.  I'd say a fairly large space since I think we've already learned a lot from the MobileBridge iOS workshops (here are the debriefs from those workshops:  [http://tinyurl.com/MB-iOS-debriefs](http://tinyurl.com/MB-iOS-debriefs)).

Once the organizers and venue/sponsor pick the dates (teacher training, Fri installfest, Sat workshop), then we can hold a big teacher training and kick off the Android-side of MobileBridge.

**Comment by mydiemho** [comment]
I did the Android bootcamp and is happy to help out anyway I can.

**Comment by nidhi1608** [comment]
I would be happy to teach and organize as well. Really excited this initiative is taking shape.

**Comment by rogerhu** [comment]
I can offer the location if @nidhi1608 and @ari are teaching..and want to use the Hearsay Social offices at China Basin...my only constraint is that it has to happen in June or later... :)

**Comment by paulinar** [comment]
I'd love to help out as a TA (walking around and helping the students, answering any questions they may have). :)

**Comment by kmolo** [comment]
@tensory @vibhorB @mydiemho @nidhi1608 @paulinar -- awesome, we have our organizers for the pilot Android workshop! If you would email me at mobilebridgesf AT gmail DOT com and include where you are geographically, then we can setup either an in-person meeting or a Google Hangout for sometime in the next 1-2 weeks.  @nesquena and possibly @rogerhu would be cool if you could join us.

@rogerhu how big are the Hearsay Social offices? Ideally we're looking for spaces where we could break out multiple groups of 10, by experience level.  Whiteboards & projectors are nice.  Also a space for a supervised play area for attendees' children -- attendees indicate if they need childcare when they RSVP along with the age of their children; parents are asked to bring everything the children need to keep them entertained, and we recruit volunteers to supervise the playspace.

Also, would Hearsay Social be able to provide the food? For one of our [previous iOS workshops](https://www.bridgetroll.org/events/132), the total cost of food was just under $800.

**Comment by sonamsharma** [comment]
@kmolo @nesquena If still there is room for TA i would be happy to take that role :)

**Comment by kmolo** [comment]
@sonamsharma there definitely will be room. once we have a confirmed venue & number of students who can attend, we'll need a lot of instructors/TAs to support a good learning ratio (which from prior experience seems to be 2-4 students per instructor/TA & less than 10 students per group).

**Comment by sonamsharma** [comment]
@kmolo Cool I will be looking forward to it.

**Comment by kmolo** [comment]
Polling for when to hold the first organizer meeting.  If you'd like to participate, complete this doodle by Sunday night:

http://doodle.com/pn3g7879r9um9wk9

**Comment by kmolo** [comment]
Our first organizer meeting will be on Tue Apr 28th 7-8pm in San Francisco near the Giants' AT&T ballpark (send an email to *mobilebridgesf AT gmail DOT com* if you want to join us...so we know how many people are coming, since we'll be ordering food).

Here's the draft agenda:  [http://tinyurl.com/pilot-Android-kickoff-mtg](http://tinyurl.com/pilot-Android-kickoff-mtg)

**Comment by kmolo** [comment]
Opened an Issue under the '[androidbridge](https://github.com/mobilebridge/androidbridge)' repo to discuss edits to the curriculum prior to this pilot workshop:

https://github.com/mobilebridge/androidbridge/issues/1

**Comment by kmolo** [comment]
yay! @BrainScraps and @nidhi1608 have volunteered to co-organize this workshop

**Comment by kmolo** [comment]
Yay! [Hearsay Social](https://www.google.com/#q=hearsay+social) is able to host:

- __Teacher Training__: Sat, Aug 1st
- __InstallFest__: Fri, Aug 7th
- __Workshop__: Sat, Aug 8th

...now we're still looking for a sponsor to cover additional costs (food, etc) which run about $400-$900.

Does anyone work for a place that would be interested in sponsoring the pilot MobileBridge Android workshop?

**Comment by paulinar** [comment]
Let me see if Uber can sponsor - I'll get back to you on this!

On Tue, Jun 16, 2015 at 7:59 AM, kmolo <notifications@github.com> wrote:

> Yay! Hearsay Social <https://www.google.com/#q=hearsay+social> is able to
> host:
>
>    - *Teacher Training*: Sat, Aug 1st
>    - *InstallFest*: Fri, Aug 7th
>    - *Workshop*: Sat, Aug 8th
>
> ...now we're still looking for a sponsor to cover additional costs (food,
> etc) which run about $400-$900.
>
> Does anyone work for a place that would be interested in sponsoring the
> pilot MobileBridge Android workshop?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobilebridge/organizing/issues/7#issuecomment-112461936>
> .
>



-- 
Paulina Ramos

**Comment by paulinar** [comment]
Update: unfortunately, Uber can't offer sponsorship for the workshop at
this time, but I'm sure Uber can provide a venue/space to host a future
workshop.

On Thu, Jun 18, 2015 at 9:26 PM, Paulina Ramos <m.paulina.ramos@gmail.com>
wrote:

> Let me see if Uber can sponsor - I'll get back to you on this!
>
> On Tue, Jun 16, 2015 at 7:59 AM, kmolo <notifications@github.com> wrote:
>
>> Yay! Hearsay Social <https://www.google.com/#q=hearsay+social> is able
>> to host:
>>
>>    - *Teacher Training*: Sat, Aug 1st
>>    - *InstallFest*: Fri, Aug 7th
>>    - *Workshop*: Sat, Aug 8th
>>
>> ...now we're still looking for a sponsor to cover additional costs (food,
>> etc) which run about $400-$900.
>>
>> Does anyone work for a place that would be interested in sponsoring the
>> pilot MobileBridge Android workshop?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mobilebridge/organizing/issues/7#issuecomment-112461936>
>> .
>>
>
>
>
> --
> Paulina Ramos
>



-- 
Paulina Ramos

**Comment by kmolo** [comment]
@paulinar thanks for looking into this!  good to know that uber is interested in possibly hosting a future workshop

**Comment by kmolo** [comment]
@BrainScraps @nidhi1608 any updates on this workshop?

If you pick the target student population & create the BridgeTroll event, then we can start recruiting instructors/TAs.

**Comment by kmolo** [comment]
So this workshop is scheduled one month from now, and my one responsibility to this workshop is to find funding for food, and I'm failing at that, which is increasing the likelihood that it won't happen.  So let's decide what to do.

1/ we can find a sponsor to fund the food
  - in the past, we've spent:
    - workshop breakfast:  $150-$200 
    - workshop lunch:  $450-600
    - first drink at after-party to thank volunteers:  (don't have this number right now)
    - teacher training (pizza & drinks):  (don't have this number right now)
    - snacks at installfest:  (don't have this number right now)

...I'd personally be willing to pay for childcare costs & the pizza at the teacher training, but can't cover the workshop food.

2/ we could scale back the food provided -- lunch only?

3/ we could ask everyone to brown bag it

4/ we could scale back the length of the workshop

5/ we could look into finding a company which could/would host & cover food costs

6/ ...(many other possibilities)...

__@BrainScraps @nidhi1608 this is your workshop, what do you want to do?__

/cc @rogerhu @nesquena @ultrasaurus

**Comment by BrainScraps** [comment]
oh no. I'm giving these options some thought and I'll get back with you this evening. Sorry I've been sort of out of the loop for a bit.

**Comment by nidhi1608** [comment]
@kmolo, @BrainScraps - I think finding a company that can host and provide food is probably the best. There are a few companies like Chatboost that provide food at least for our Codepath meetups.

**Comment by jeffreybergier** [comment]
hey @kmolo and others. I was just checking in to see if a venue for android workshop was still MIA?

**Comment by kmolo** [comment]
@jeffreybergier and others:

Got a grant to cover the food, so we're still on at Hearsay Social.

Up to a million little things for tonight's CodePath demo day that I'm responsible for organizing, and then will write up some more stuff for MobileBridge.  Sarah Allen & I had a good brainstorming sessions about how to set MobileBridge up for success for organizing & fund-raising.

Basically we're all set for this workshop & the Sept iOS workshop, but then need hosts & sponsors for anything after that.  But all very do-able.

**Comment by jeffreybergier** [comment]
ok. good to hear. I was beginning to freak out a bit. I'm going to see if I can drum up some interest at my company about hosting these kinds of things. Previously its been really hard because we have strict security policies enforced by Federal government (because they're a major customer) but I know Marketing has wanted to spread the name a bit, and this is the perfect way.

**Comment by kmolo** [comment]
Event is published on BridgeTroll:

https://www.bridgetroll.org/events/177

**Comment by kmolo** [comment]
@lilliealbert sorry to ping you, but our latest event (the pilot Android workshop) starts next Sat (8/1), but is still unpublished on Bridgetroll:

https://www.bridgetroll.org/events/177

...who are the BridgeTroll admins that I should be pinging, instead of you?

**Comment by lilliealbert** [comment]
@kmolo — I never got the "There's a new event waiting to be published" email for that workshop, I'm not sure why. (I just tested all the attendee-facing emails, and those are working just fine.)

So, thanks for the ping & the workshop is now published!

We don't really have Bridge Troll admins exactly — I'd like to get a few more people on board, but for now it's fine just to ping me, @tjgrathwell, or @rachelmyers.

**Comment by kmolo** [comment]
@lilliealbert thanks!

**Comment by kmolo** [comment]
We're on a roll with this workshop

- awesome space & great partners at Hearsay Social ( @rogerhu and company )
- awesome group of collaborators working on the curriculum https://github.com/mobilebridge/androidbridge/issues/1
- there's already a waitlist for students
- there's already a great bunch of instructors signed up
- there's already two experienced (with Railsbridge & MobileBridge) childcare providers confirmed

...just looking for 3 more instructors/TAs -- invite your friends or any other awesome Android devs that you haven't had the chance to hang out with lately.  Building the social community side of MobileBridge....

:sparkles: :sparkles: :sparkles:

**Comment by rogerhu** [comment]
Just an FYI that BART is closed on Aug. 1 and Aug. 2 from Oakland to SF -- http://www.sfgate.com/bayarea/article/BART-s-message-on-transbay-tube-shutdown-Stay-6397773.php.  @paulinar we hope you can find alternate ways of making it over!

**Comment by rogerhu** [comment]
Correction: all of BART is shutdown from the East Bay on August 1.    https://www.bart.gov/news/articles/2015/news20150624-0

"BART is encouraging travelers to plan ahead and to find alternate means of transportation across the Bay during two upcoming closures of transbay train service. BART will close the West Oakland Station and will not run trains between West Oakland and Embarcadero stations the first weekend in August and during Labor Day weekend while we repair a critical section of track near the Transbay Tube.

BART will offer lifeline bus service between 19th Street in Oakland and the Temporary Transbay Terminal in San Francisco, but the buses are intended only for those who have no other options. The buses will carry customers from 19th Street Station in Oakland to the Temporary Transbay Terminal in San Francisco (a 2 block walk to the Embarcadero Station) or from there back to the East Bay.  There will be no additional charge for the bus. The bus bridge will cause 1 to 2 hour delays for some customers."

**Comment by BrainScraps** [comment]
Good looking out, @rogerhu

**Comment by tensory** [comment]
Is teacher training located at Uber or at Hearsay today? Guessing Hearsay but would like to confirm. Thanks!

**Comment by rogerhu** [comment]
At Hearsay.  See you this afternoon?

**Comment by tensory** [comment]
Yes, will be attending to learn how it's done :)

**Comment by kmolo** [comment]
The Intro & Closing slides for this particular workshop:

[MobileBridge Android Introduction](https://docs.google.com/presentation/d/1Rnjn_ZnTO6bdgTQv3XER3eCEne9D92pyZ3wV0HSeYJY/edit#slide=id.p)

[MobileBridge Android Closing](https://docs.google.com/presentation/d/1UwJDNSKDdMMZ_B3OQGMbfIjaRTR3ESrBelP1NRNJD4U/edit#slide=id.p)

...to be edited.

/cc @rogerhu

**Comment by kmolo** [comment]
Planning post-workshop hack night with @mdcramer 

Here's the Doodle to pick a time:  

http://doodle.com/c4mmpvkw8xby55qn

...with __Wed 8/12, Thu 8/13, and Wed 8/26__ being the top contenders.

If you can attend as a mentor, add yourself to the Doodle.  Unless there is a groundswell of volunteer mentors for next week, that's too quick to organize.

Talking with Dev Bootcamp (633 Folsom St, San Francisco) about hosting.

/cc @animan1 @anubharadwaj @BrainScraps @calren @jangelroa @kgleong @kmolo @martasmith @mwells29 @ndun @nesquena @nidhi1608 @paulinar @rogerhu @rtteal @sonamsharma @tensory @vibhorB @wapples

**Comment by kmolo** [comment]
Confirmed Android hack night at Dev Bootcamp (633 Folsom St, SF) for Wed evening 8/26!

**Comment by kmolo** [comment]
@rogerhu @nesquena @wapples @BrainScraps 

Thinking of file sizes & wifi download capacity, s there any software that we should bring pre-loaded onto flash drives for the installfest?

FYI, so far I've only had 1 student complete the installation checkout via email, so we should have a full house on Friday night.

---
Also @josephclaymiller had asked which versions students had been installing, and this is what I've seen so far:

  - Java version 1.8.0_51
  - git version 2.4.3
  - Android Studio version 1.2.2. Build 141.1980579
  - Genymotion version 2.5.2

Which version of Android will be having everyone use use on Sat?  Android 5.0 (API 21)?

**Comment by rogerhu** [comment]
We will have WiFi caps lifted so I don't think USB flash drives are needed...[Stuxnet](http://www.cnet.com/news/stuxnet-delivered-to-iranian-nuclear-plant-on-thumb-drive/) comes to mind...

API 21 is fine.  Genymotion + Android API 16 devices are fine.

Android Studio v1.3 is what will be used.   There are slight differences (i.e. AppCompatActivity instead of ActionBarCompatActivity).  It's not a huge deal but you apparently lose any plugins since it creates a new home for all preferences.  The latest download should be Android Studio 1.3.   Android Studio v1.2 or above should be fine.

**Comment by kmolo** [comment]
I always am running around doing too many things at once at the workshop sessions, and forget to take pictures & tweet [@MobileBridgeSF](https://twitter.com/mobilebridgesf) -- a la at our amazing teacher training session.

If teachers/TAs/volunteers remember/enjoying taking pictures, please do & tweet them including the [@MobileBridgeSF](https://twitter.com/mobilebridgesf) handle.  Definitely want to document the awesome-ness that this workshop will be.  Especially the killer student/volunteer ratio that is shaping up.

**Comment by mdcramer** [comment]
I do a little bit of very armature photography if you'd like for me to take
some pictures.

**Comment by kmolo** [comment]
@mdcramer that would be awesome!

**Comment by kmolo** [comment]
GitHub Issue for Hack night:  https://github.com/mobilebridge/organizing/issues/13

**Comment by rogerhu** [comment]
For advanced classes that want to do something besides a ToDo app, I made this deck for the Rotten Tomatoes walkthrough: http://slides.com/rogerhu/deck/#/

The goal obviously is to get people to play with RelativeLayout/LinearLayout, learn ListView without networking (and then add in later), and then to demonstrate (time allowing) intents.  The guide links are available for people to work through building the app.

**Comment by kmolo** [comment]
Debriefs:
- volunteers: http://tinyurl.com/MB-Android-20150808-volunteers
- students: http://tinyurl.com/MB-Android-20150808-students

**Comment by mdcramer** [comment]
Katherine - Should I be signing up for a list somewhere so that you don't
have to explicitly put me on CC?

This is great feedback from the students, by the way. It was definitely the
best Android event I've been to so far.

**Comment by kmolo** [comment]
Just Replied-All to Isaac & Roger's original conversation was over email.  

But, going forward, the plan is to just post in GitHub issue, and then everyone who was ever @-ed ("At-ed") will get the email automatically.

---
closing this issue, and moving over to the Wed 8/26 hack night Issue https://github.com/mobilebridge/organizing/issues/13

**Comment by mdcramer** [comment]
Ah, OK, thanks. So I guess that means I'm automatically in.
