### ISSUE TITLE
SF iOS workshop (26-Sep-2015)

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/organizing#9]
Let's get the ball rolling for our next SF iOS workshop -- here's what we need to do!

A few months out:
- [x] Find a venue and sponsor for the workshop. Sponsoring the workshop costs between $400 and $900, depending on the size of the workshop. Space-wise, we usually split the students up into separate class levels, so having access to multiple workspaces would be nice (and if possible, projectors & whiteboards). Additionally, we like to offer students the option to bring their children with them (we recruit additional volunteers to help supervise so the parents can focus on coding).
  - __[Pivotal](http://pivotal.io/)__, which has a great space & has been a great Railsbridge sponsor, is on board!
  - Dates:
      - __Teacher Training__: Sun 9/13 3-6:30pm
      - __InstallFest__: Fri 9/25 6:30-7:30pm
      - __Workshop__: Sat 9/26 9am - 5pm

- [x] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)
  - yay! @imju and @jeffreybergier have volunteered to co-organize this workshop

- [x] Select the target student population for the workshop. Our workshops reach out to a group of people that are underrepresented in the community. That might be women, people of color, non-native English speakers, LGBTQIA communities, or other marginalized groups.

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [x] Work together to set an RSVP limit that works for everyone
- [x] Review and, if necessary, revise the computer setup instructions (newer versions, etc)
- [x] Post the workshop to [Bridge Troll](https://www.bridgetroll.org/events/182)
  - https://www.bridgetroll.org/events/182
- [ ] Post the workshop to appropriate Meetup group(s) for publicity 
  - Tip: create event on Meetup with no open RSVPs, so interested folks have to follow the link to the BridgeTroll event to register

Once students start registering:
- [x] arrange childcare, if requested

One to two weeks out, we can:
- [x] Plan a teacher training
  -  this time we're going to have a big teacher training  to train up a lot of new instructors/TAs and organizers, and encourage our former students to come back as instructors/TAs to keep learning
- [x] Order breakfast
- [x] Order lunch
- [x] Find a good place for the afterparty

After the workshop, we can:
- [x] Party! :tada:   
- [ ] Retro
- [ ] Write a blog post

:tulip:

**Comment by kmolo** [comment]
Getting the ball rolling for our next iOS workshop in SF. Looking for everything:

 - 2 co-organizers
 - a venue/sponsor, ideally the same organizations (for simplicity), best not an organizer (for sanity)

Anyone interested in organizing the next workshop?
Does anyone know a company which would be interested in hosting/sponsoring (possibly their own)?

**Comment by kmolo** [comment]
__[Pivotal](http://pivotal.io/) is on board to host/sponsor -- woohoo!__  

In discussions to pick dates in Sept 2015.  

Still need a pair of organizers.

**Comment by kmolo** [comment]
Yay! @imju and @jeffreybergier have volunteered to organize this Sept 2015 workshop.  September dates still under discussion with Pivotal.

Like we did before the pilot workshop, this time we're going to have a big teacher training on a Saturday or Sunday earlier in the month, to train up a lot of new instructors/TAs and organizers, to build up the size & the social chemistry of our community.

**Comment by russbishop** [comment]
I should be able to help teach or TA for this one

**Comment by mrh-is** [comment]
Same here, happy to TA/teach!

**Comment by yskamoona** [comment]
I would love to help organize this workshop too, but I won't be available for the workshop weekend though. I can also help out with teacher training. @jeffreybergier and @imju, is that ok?

**Comment by imju** [comment]
Thank you, Yousra and Michael for stepping up!

Bridge Troll event is almost done and just need final reviews.  I can
publish the schedule here so that you can plan it ahead.

9/6 Teacher Training 4-7:30pm -- this session is only for
instructors/TAs/volunteers, no students please
9/25 InstallFest 6pm-7pm
9/26 Workshop 9:30am-5pm

**Comment by yskamoona** [comment]
Hi Imju, if you can direct me where I can find that it would be great.

**Comment by imju** [comment]
5th Mobile Bridge workshop for iOS is live for selective audience!

The event sponsored by Pivotal live on bridgetroll site and it is available
in the following link.

https://www.bridgetroll.org/events/182

We sent this private link to our target audience for them to sign up early
before it is available publicly.

Please sign up today for becoming teacher or TA and send it to your friends
interested in mobile development.

Hope to see you all!
Imju, Jeff, Katherine

**Comment by kmolo** [comment]
@aparnarsjain @devhut @dmtsui @dvidsilva @joekim @kristen @LauraKirby @mludowise @mmesarina @mrh-is @mtitolo @rajatb @russbishop @salilmalkan @shawnyapa @stansey @steffi06 @StephanieSzeto @timothy1ee @tjgrathwell @ultrasaurus @yskamoona

looking for additional instructors for next MobileBridge iOS workshop that @imju & @jeffreybergier are organizing at __Pivotal__ (875 Howard St, SF):

https://www.bridgetroll.org/events/182
- __Teacher Training__: Sun 9/13 3-6:30pm
- __InstallFest__: Fri 9/25 6:30-7:30pm
- __Workshop__: Sat 9/26 9am - 5pm

If you'd be interested/available, please RSVP as a volunteer by this Sun 8/16.

---
Also, as we're coming up on the year anniversary of the founding of MobileBridge, we want to reach out & __expand the circle of teachers/TAs beyond the founding core__, so this becomes a sustainable volunteer organization.

If everyone would reach out to 3-4 people:
 - co-workers who are iOS devs/designers
 - friends who you haven't seen in awhile, that you would enjoy volunteering with
 - anyone who would be interested in the *Bridge mission to diversify the developer/designer community to reflect the larger user community

So much has been accomplished this first year:
 - 4 iOS workshops, 1 Android workshop
 - 3 iOS workshops in the planning phase, 2 Android workshops in the planning phase
 - our workshops are offering childcare
 - we've started hosting post-workshop hack nights to support students as they continue making apps
 - opened MobileBridge categories on the Bridge Foundry Discourse forum http://discourse.bridgefoundry.org/categories

Pretty amazing!

...and that didn't happen all by itself.  We collectively made that happen, and you should be proud of being a part of such an endeavor.  Many hands make light work, so please help expand the circle and the impact.

**Comment by mtitolo** [comment]
I'm out of town that weekend. Have fun!

**Comment by russbishop** [comment]
I signed up to teach. My sister in law is due to have her baby right around 9/6 so it's 50/50 I won't be able to attend teacher training but if that's the case I can catch up on the curriculum before the workshop.

**Comment by kmolo** [comment]
thanks @russbishop we definitely will be happy to have you whenever we can.  I hope the birth is a happy/healthy one, so you can enjoy your new niece/nephew!

still looking to improve our student-teacher/TA ratio, so if folks can talk to their co-workers & friends to help expand the circle of teachers/TAs that would greatly appreciated!

**Comment by mludowise** [comment]
I'll spread the word at Hearsay Social and hopefully get a few more people.

**Comment by yskamoona** [comment]
The workshop weekend freed for me, so I added my name for the volunteer list.

**Comment by yskamoona** [comment]
Hmm I just saw that you guys requested we sign up as volunteers by August 16th. Is the list still open?

**Comment by jeffreybergier** [comment]
totally. we need more volunteers. We're happy to have you :)

**Comment by yskamoona** [comment]
Sounds good. Thanks!

**Comment by timothy1ee** [comment]
I found a few more volunteers, sending your way!

**Comment by jeffreybergier** [comment]
@timothy1ee awesome! thanks so much!

**Comment by kmolo** [comment]
FYI, there is no BART service between the East Bay and San Francisco this weekend (i.e. when the MobileBridge iOS Teacher Training is happening): https://www.bart.gov/

/cc @dominic

**Comment by dominic** [comment]
Yeah :( I'm doing my part and not crossing the bay Sunday. Hopefully I can still TA for the actual workshop.

**Comment by mrh-is** [comment]
I'm out of town for the teacher training this weekend, but I can get the info from @jeffreybergier when I'm back. :+1:

**Comment by kmolo** [comment]
@dominic definitely. 

---
@mrh-is absolutely.  plus you've volunteered at the last workshop, so that helps.

**Comment by kmolo** [comment]
Which Xcode do we want students to have:

https://developer.apple.com/xcode/downloads/

https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites

**Comment by jeffreybergier** [comment]
By the time of the workshop, Xcode 7 will be out. I think it will go final on September 9th Apple event. If so we can send out a message to all students that Xcode 7 is it. It runs on OS X Yosemite and El Capitan. Then during the install feat we can make sure everyone has it. If there are still OS X Mavericks users, Xcode 6 will still work (with possible extra attention required by TA's)

**Comment by mludowise** [comment]
Xcode 7 allows you to run apps on your device without the need of a developers license, so I highly recommend it because of this. This way the students will be able to walk out with the app they've built on their device, if they have one.

It's set to be officially released this Wednesday but I went ahead and downloaded the beta last night and it's quite stable. I was able to run an app on my phone without a license, I just needed to sign in with my Apple ID.

**Comment by jeffreybergier** [comment]
Oh yes. I forgot about this. If students have iOS devices we should definitely try to get this working for them at the install fest.

**Comment by ultrasaurus** [comment]
I will be out of town for both teacher training & the workshop.  Sorry to miss this!

**Comment by kmolo** [comment]
Xcode 7 still appears to be beta.  Any word on when non-beta might be available, to pass along to students who are planning to do the virtual installation over email?

**Comment by jeffreybergier** [comment]
@kmolo Apple has released the GM build. This build is expected to go release on September 16th when iOS9 is officially released.

That being said: I just tried to download the GM seed with a free AppleID (not a developer account, not a paid developer account) and it was letting me doing it after agreeing to an EULA.

If students want to prioritize their time and do this before Sept 16th, they can follow this link: https://developer.apple.com/xcode/download/ and click
<img width="1074" alt="xcode_-_downloads_-_apple_developer" src="https://cloud.githubusercontent.com/assets/7349616/9830028/4197188c-58d4-11e5-9d80-eef4640bf601.png">

**Comment by kmolo** [comment]
okay, updated the instructions with your image:

https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites

**Comment by mludowise** [comment]
XCode 7 is expected to be released on the 16th, so they should not need to download the seed at that point, hopefully. We'll probably need to update the instructions on the 16th accordingly.

**Comment by kmolo** [comment]
@jeffreybergier [shared](https://github.com/mobilebridge/organizing/issues/15#issuecomment-138641711):

> here is the chat thing I was talking about that makes it super easy to share links in classrooms. https://tlk.io/

**Comment by kmolo** [comment]
Last minute details?

 - information to add to closing slides:
    - Discourse forum: [http://discourse.bridgefoundry.org/c/mobilebridge-ios-help](http://discourse.bridgefoundry.org/c/mobilebridge-ios-help)
    - post-workshop Hack Night at [PlanGrid](http://www.plangrid.com/) (3265 17th St, Suite 404, SF) on Wed Oct 10th 6-9pm (mobilebridge/organizing Issue https://github.com/mobilebridge/organizing/issues/10) -- thanks @russbishop 
 - food:
    - need help picking up coffee travelers in the morning from the Starbucks ([120 4th St btw Mission & Minna](http://www.starbucks.com/store-locator/search/location/875%20Howard%20St%2C%20San%20Francisco%2C%20CA%2094103%2C%20USA)) around the corner from workshop (875 Howard St btw 4th & 5th)
        - too much for 1 person to carry, need 1 other person (we'd meet there at 8am, so would be over to Pivotal in time for Noah's bagel food delivery btw 8:30-8:45am)

What other last minute details do we need to handle?

/cc @imju @jeffreybergier

**Comment by imju** [comment]
I can come to Starbucks around that time.  I will arrive Powell at 7:55 am.


Thanks,
Imju
Sent from G4

<div>-------- Original message --------</div><div>From: kmolo <notifications@github.com> </div><div>Date:09/25/2015  11:05 AM  (GMT-08:00) </div><div>To: mobilebridge/organizing <organizing@noreply.github.com> </div><div>Cc: imju <imjubyon@gmail.com> </div><div>Subject: Re: [organizing] SF iOS workshop (26-Sep-2015) (#9) </div><div>
</div>Last minute details?

information to add to closing slides:
Discourse forum: http://discourse.bridgefoundry.org/c/mobilebridge-ios-help
post-workshop Hack Night at PlanGrid (3265 17th St, Suite 404, SF) on Wed Oct 10th 6-9pm (mobilebridge/organizing Issue #10) -- thanks @russbishop
food:
need help picking up coffee travelers in the morning from the Starbucks (120 4th St btw Mission & Minna) around the corner from workshop (875 Howard St btw 4th & 5th)
too much for 1 person to carry, need 1 other person (we'd meet there at 8am, so would be over to Pivotal in time for Noah's bagel food delivery btw 8:30-8:45am)
What other last minute details do we need to handle?

/cc @imju @jeffreybergier

**Comment by kmolo** [comment]
Good news!  Pivotal going to have us use their awesomely industrial/easy-to-use coffee maker along with a bag of coffee that's already there.  So scratch the Starbucks appointment in the morning - yay!

But thanks @imju

**Comment by mludowise** [comment]
Running a little late, but I should be there in about 10 min.

**Comment by imju** [comment]
I would like to send out a wrap up emails to students with the urls for repos.  Let me know what you think. 

@jeffreybergier What was the url for the web app like IRC?  I wish we have used this in our class because it would help speed up class like API key sharing or some advanced concept that can be explained later time.  

@kmolo @jeffreybergier

**Comment by kmolo** [comment]
@imju 

> I would like to send out a wrap up emails to students with the urls for repos. Let me know what you think.

Which repos in addition to the content list in the "[MobileBridge iOS] post-workshop app building...join us!" email?

**Comment by imju** [comment]
@kmolo If there is a content list already including the repos that we
taught that you intend to send out, you can ignore this.

**Comment by imju** [comment]
@kmolo 
https://github.com/mobilebridge/iosbridge/wiki/Post-Workshop-Resources 
Is this what you were referring to?  This is very outdated it points to codepath repo.  If there is no newer one, then we have to make this up to date.  
Let me know if it is the case.  I will make the changes.

@jeffreybergier IRC tool?

**Comment by kmolo** [comment]
@imju we should  definitely update 
https://github.com/mobilebridge/iosbridge/wiki/Post-Workshop-Resources 

Additionally, you were CC'ed on the email, but here are the repos listed:

---
Here are the curricula that we were using at the workshop:

- Tip Calculator (Swift):  https://github.com/mobilebridge/iosbridge-tipster-swift
- Rotten Tomatoes (Swift): https://github.com/mobilebridge/iosbridge-rottentomatoes
- Rotten Tomatoes (Objective-C): https://github.com/codepath/ios_guides/wiki/RottenTomatoes-Tutorial

...as you can see these guides are really for the instructors, not detailed step-by-step guides to build these apps.

Additionally, here are some iOS development learning resources for you:

- Ray Wenderlich iOS Tutorials:  http://www.raywenderlich.com/category/ios
- Stanford CS193P iPhone Application Development course on iTunes U:
  - [Developing iOS 8 Apps with Swift](https://itunes.apple.com/us/course/developing-ios-8-apps-swift/id961180099) -- even though it's currently the older Xcode/iOS/Swift, it's still worth watching because most of the APIs haven't changed
  - [Developing iOS 7 Apps with Objective-C](https://itunes.apple.com/us/course/developing-ios-7-apps-for/id733644550)
- the CodePath iOS guides:
  - CodePath iOS Guides:  http://guides.codepath.com/ios
  - CodePath iOS Guides for Designers:  http://guides.codepath.com/ios/Designer-Guides
- videos made by Tim Lee, one of the original curriculum developers, walking you thru how to make the Tip Calculator app:
  - (Swift version) https://vimeo.com/102084767
  - (Obj-C version) https://vimeo.com/74764846
- samples of finished apps:
  - (Objective-C) Tip Calculators:
    - https://github.com/codepath/ios_tipster
    - https://www.dropbox.com/s/m5ul5992fddc7h1/Tip%20Calculator%20-%20Aaron%20Carumbula.zip?dl=0
    - https://www.dropbox.com/s/hdtxwusbqpefq17/EatOut%20-%20Hoyd.zip?dl=0
  - (Objective-C) RottenTomatoes:
    - https://github.com/codepath/ios_tomatoes
- a step-by-step guide for the Objective-C version of the Tip Calculator that Jeff Bergier created:
  - https://github.com/jeffreybergier/tipCalculatorGuide/wiki/Tip-Calculator-in-Objective-C-Guide
- Code School's [Try Objective-C](https://www.codeschool.com/courses/try-objective-c) training game

**Comment by imju** [comment]
Sorry that I missed this @kmolo ( I am pretty busy because I am going out
of town for a few weeks).

The Post workshop page is updated now.

**Comment by kmolo** [comment]
@jeffreybergier and I still need to post the debriefs, but for now will close this issue.
